holograms:
  spawn:
    world: 'world'
    x: -24.5
    y: 101.5
    z: 477.5
    text:
    - '&dДобро пожаловать на &eЖизнь Животных'
    - '&dот сервера &a&lGrendCity&d!'
    - '&0'
    - '&3На данном режиме Вы - животное, которое Вы выбрали!'
    - '&3Для начала Вам нужно найти &7потерянную овечку'
    - '&3и отнести её в &7приют&3. Когда Вы накопите &6300р&3, Вы'
    - '&3сможете купить свой первый бизнес (&2Колодец&3)!'
    - '&1'
    - '&bДоступные команды: &5/help'