name: MavenAnimalsLive
author: iBuseWinner
version: 0.2.103_369
main: ru.ibusewinner.animals.MainAnimals
description: AnimalsLive plugin!

commands:
  choose:
  info:
  buy:
  show:
  KAd5WlBYtyUhqubXaHIwmcXb:
  respawn:
  alboost:
  algive:
  alshow:
  leaderboard:
  alholo:
  levelup:
  algc:
  donate: